# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - winequality

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://winequality.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1438315dd0254edaac42dc6f92af8353 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_caaf5c83764741e299f2abbd103a4b9f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: winequality.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1438315dd0254edaac42dc6f92af8353 }}/winequality:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'winequality'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_715a595c3ffc45028327c1390f960c9d }}
        images: 'winequality.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1438315dd0254edaac42dc6f92af8353 }}/winequality:${{ github.sha }}'